"""
DSL module - imports the new text-based DSL parser
This replaces the old function-based DSL system.
"""

# Import the new DSL components
from dsl_parser import DSLParser, DSLExecutor, DSLRule, MockLLMResponse

# Backward compatibility - these are now text strings instead of function lists
AGGRESSIVE_PROGRAM_TEXT = """
1) IF PROJ.NEAR#0.TTI ≤ 0.25 : DODGE RIGHT +5 ; FIRE OFF +5
2) IF PROJ.NEAR#0.TTI ≤ 0.5 AND PROJ.NEAR#0.rel_towards > 0 : DODGE LEFT +3
3) IF ENEMY.FRONT#0.DIST < 12 AND SELF.can_fire = 1 : ROTATE TO TARGET ENEMY.FRONT#0 +5 ; FIRE ON +5
4) IF ENEMY.FRONT#0.DIST < 8 AND ENEMY.FRONT#0.hp ≤ 50 : ROTATE TO TARGET ENEMY.FRONT#0 +5 ; FIRE ON +5 ; MOVE FWD SPEED 1 +3
5) IF ENEMY.NEAR#0.hp ≤ 30 AND ENEMY.NEAR#0.DIST < 15 : ROTATE TO TARGET ENEMY.NEAR#0 +4 ; FIRE ON +4
6) IF ENEMY.FRONT#1.VALID = 1 AND ENEMY.FRONT#1.DIST < 12 : ROTATE TO TARGET ENEMY.FRONT#1 +3 ; FIRE ON +3
7) IF ENEMY.NEAR#1.VALID = 1 AND ENEMY.NEAR#1.DIST < 10 : ROTATE TO TARGET ENEMY.NEAR#1 +2 ; FIRE ON +2
8) IF enemy_count_near ≥ 2 AND SELF.hp > 60 : MOVE FWD SPEED 1 +4 ; FIRE ON +3
9) IF enemy_count_near ≥ 3 : ROTATE TO HEADING 180 +5 ; MOVE FWD SPEED 0.5 +2
10) IF ENEMY.FRONT#0.DIST > 15 AND ENEMY.FRONT#0.VALID = 1 : MOVE FWD SPEED 1 +4
11) IF ENEMY.FRONT#0.DIST > 8 AND ENEMY.FRONT#0.DIST < 15 : MOVE FWD SPEED 0.5 +2
12) IF SELF.speed > 1.5 AND ENEMY.FRONT#0.DIST < 6 : MOVE FWD SPEED 0.5 +1
13) IF FRIEND.NEAR#0.DIST < 3 AND FRIEND.NEAR#0.hp < 40 : MOVE BACK SPEED 0.5 +2
14) IF FRIEND.NEAR#0.hp ≤ 20 AND ENEMY.FRONT#0.DIST < 10 : ROTATE TO TARGET ENEMY.FRONT#0 +4 ; FIRE ON +4
15) IF ff_risk_front = 1 : FIRE OFF +5
16) IF SELF.hp ≤ 50 AND enemy_count_near ≥ 2 : DODGE RIGHT +3 ; MOVE BACK SPEED 1 +3
17) IF SELF.hp ≤ 30 : ROTATE TO HEADING 180 +5 ; MOVE FWD SPEED 1 +5 ; FIRE OFF +5
18) IF SELF.hp ≤ 15 : DODGE LEFT +5 ; MOVE FWD SPEED 1 +5
19) IF ENEMY.FRONT#0.VALID = 0 AND ENEMY.NEAR#0.VALID = 0 : ROTATE TO HEADING 90 +2 ; MOVE FWD SPEED 1 +1
20) IF SELF.fire_cooldown > 0 AND ENEMY.FRONT#0.DIST < 10 : MOVE LEFT SPEED 0.5 +1
"""

DEFENSIVE_PROGRAM_TEXT = """
1) IF PROJ.NEAR#0.TTI ≤ 0.25 : DODGE RIGHT +5 ; FIRE OFF +5
2) IF PROJ.NEAR#0.TTI ≤ 0.5 AND PROJ.NEAR#0.rel_towards > 2 : DODGE LEFT +4
3) IF PROJ.NEAR#1.TTI ≤ 0.4 : DODGE RIGHT +3
4) IF ENEMY.FRONT#0.DIST < 18 AND ENEMY.FRONT#0.DIST > 6 AND SELF.can_fire = 1 : ROTATE TO TARGET ENEMY.FRONT#0 +4 ; FIRE ON +3
5) IF ENEMY.FRONT#0.DIST < 8 : MOVE BACK SPEED 1 +5 ; FIRE ON +2
6) IF ENEMY.FRONT#0.DIST < 5 : MOVE BACK SPEED 1 +5 ; DODGE LEFT +4
7) IF ENEMY.NEAR#0.DIST < 6 AND ENEMY.NEAR#0.hp > 60 : MOVE BACK SPEED 1 +4
8) IF ENEMY.FRONT#1.VALID = 1 AND ENEMY.FRONT#1.DIST < 15 : ROTATE TO TARGET ENEMY.FRONT#1 +2 ; FIRE ON +2
9) IF enemy_count_near ≥ 2 AND SELF.hp > 40 : MOVE BACK SPEED 0.5 +3 ; FIRE ON +2
10) IF enemy_count_near ≥ 3 : ROTATE TO HEADING 180 +5 ; MOVE BACK SPEED 1 +4
11) IF SELF.hp ≤ 60 AND ENEMY.FRONT#0.DIST < 12 : DODGE LEFT +3 ; MOVE BACK SPEED 0.5 +3
12) IF SELF.hp ≤ 40 : DODGE RIGHT +4 ; MOVE BACK SPEED 1 +4 ; FIRE ON +2
13) IF FRIEND.NEAR#0.DIST ≥ 8 AND FRIEND.NEAR#0.hp > 30 : ROTATE TO TARGET VISIBLE_FRIENDS_CENTROID +2
14) IF FRIEND.NEAR#0.hp ≤ 25 AND ENEMY.FRONT#0.DIST < 10 : ROTATE TO TARGET ENEMY.FRONT#0 +3 ; FIRE ON +3
15) IF ff_risk_front = 1 : FIRE OFF +5
16) IF SELF.speed > 1.0 AND ENEMY.FRONT#0.DIST < 10 : MOVE BACK SPEED 0.5 +2
17) IF SELF.hp ≤ 30 : ROTATE TO HEADING 180 +5 ; MOVE FWD SPEED 1 +5 ; FIRE OFF +5
18) IF SELF.hp ≤ 15 : DODGE LEFT +5 ; MOVE FWD SPEED 1 +5
19) IF ENEMY.FRONT#0.VALID = 0 AND ENEMY.NEAR#0.VALID = 0 : ROTATE TO HEADING 45 +1 ; MOVE FWD SPEED 0.5 +1
20) IF SELF.fire_cooldown ≤ 0.1 AND ENEMY.FRONT#0.DIST < 15 : FIRE ON +1
"""

BALANCED_PROGRAM_TEXT = """
1) IF PROJ.NEAR#0.TTI ≤ 0.25 : DODGE RIGHT +5 ; FIRE OFF +5
2) IF PROJ.NEAR#0.TTI ≤ 0.4 AND PROJ.NEAR#0.rel_towards > 1 : DODGE LEFT +4
3) IF ENEMY.FRONT#0.DIST < 12 AND SELF.can_fire = 1 : ROTATE TO TARGET ENEMY.FRONT#0 +5 ; FIRE ON +4
4) IF ENEMY.FRONT#0.DIST < 6 AND ENEMY.FRONT#0.hp ≤ 40 : ROTATE TO TARGET ENEMY.FRONT#0 +5 ; FIRE ON +5 ; MOVE BACK SPEED 0.5 +2
5) IF ENEMY.NEAR#0.hp ≤ 35 AND ENEMY.NEAR#0.DIST < 12 : ROTATE TO TARGET ENEMY.NEAR#0 +4 ; FIRE ON +3
6) IF ENEMY.FRONT#1.VALID = 1 AND ENEMY.FRONT#1.DIST < 10 : ROTATE TO TARGET ENEMY.FRONT#1 +3 ; FIRE ON +2
7) IF ENEMY.NEAR#1.VALID = 1 AND ENEMY.NEAR#1.DIST < 8 : ROTATE TO TARGET ENEMY.NEAR#1 +2 ; FIRE ON +2
8) IF enemy_count_near ≥ 3 : ROTATE TO HEADING 270 +5 ; MOVE FWD SPEED 0.5 +3
9) IF enemy_count_near = 1 AND ENEMY.FRONT#0.DIST > 10 : MOVE FWD SPEED 1 +3
10) IF enemy_count_near = 2 AND SELF.hp > 50 : MOVE FWD SPEED 0.5 +2 ; FIRE ON +2
11) IF ENEMY.FRONT#0.DIST > 15 AND ENEMY.FRONT#0.VALID = 1 : MOVE FWD SPEED 0.5 +2
12) IF ENEMY.FRONT#0.DIST > 8 AND ENEMY.FRONT#0.DIST < 15 : MOVE FWD SPEED 0.5 +1
13) IF SELF.speed > 1.2 AND ENEMY.FRONT#0.DIST < 8 : MOVE FWD SPEED 0.5 +1
14) IF FRIEND.NEAR#0.DIST < 4 AND FRIEND.NEAR#0.hp < 50 : MOVE LEFT SPEED 0.5 +2
15) IF FRIEND.NEAR#0.hp ≤ 30 AND ENEMY.FRONT#0.DIST < 12 : ROTATE TO TARGET ENEMY.FRONT#0 +3 ; FIRE ON +3
16) IF ff_risk_front = 1 : FIRE OFF +5
17) IF SELF.hp ≤ 40 AND enemy_count_near ≥ 2 : DODGE LEFT +3 ; MOVE BACK SPEED 0.5 +2
18) IF SELF.hp ≤ 30 : ROTATE TO HEADING 180 +5 ; MOVE FWD SPEED 1 +5 ; FIRE OFF +5
19) IF ENEMY.FRONT#0.VALID = 0 AND ENEMY.NEAR#0.VALID = 0 : ROTATE TO HEADING 45 +1 ; MOVE FWD SPEED 0.5 +1
20) IF SELF.fire_cooldown ≤ 0.05 AND ENEMY.FRONT#0.DIST < 12 AND ENEMY.FRONT#0.DIST > 4 : FIRE ON +2
"""

# For backward compatibility with old imports
AGGRESSIVE_PROGRAM = AGGRESSIVE_PROGRAM_TEXT
DEFENSIVE_PROGRAM = DEFENSIVE_PROGRAM_TEXT
BALANCED_PROGRAM = BALANCED_PROGRAM_TEXT
